apiVersion: v1
kind: Pod
metadata:
  name: secret-example
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["/bin/sh", "-c", "while : ;do echo $ACCESS_TOKEN; sleep 10; done"]
      volumeMounts:
        - name: secret-volume
          mountPath: /secret
          readOnly: true
      env:
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: access-token
              key: token
  volumes:
    - name: secret-volume
      secret:
        secretName: access-token
        items:
        - key: token
          path: token-value
